AWSTemplateFormatVersion: 2010-09-09
Description: >-
  emails-inbound-service

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AccountId:
    Type: String
    Description: AWS account ID
  Bucket:
    Type: String
    Default: emails-service-storage
    AllowedValues:
      - emails-service-storage
      - emails-service-storage-test
    Description: Ruleset to create
  Ruleset:
    Type: String
    Default: emails-inbound-service
    AllowedValues:
      - emails-inbound-service
      - emails-inbound-service-test
    Description: Ruleset to create
  Subdomain:
    Type: String
    Default: bowland.link
    AllowedValues:
      - bowland.link
      - test.bowland.link
    Description: Subdomain to use for API

Resources:
  EmailBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      BucketName: !Ref Bucket
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 365
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: 'created-by'
          Value: 'emails-inbound-service'
        - Key: 'created-for'
          Value: 'emails'

  EmailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EmailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:PutObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${EmailBucket}/*'
            Principal:
              Service: ses.amazonaws.com
            Condition:
              StringLike:
                'aws:Referer':
                  - !Ref AccountId

  IncomingEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/incoming-email.handleIncomingEmail
      CodeUri: './dist'
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 90
      Description: Incoming SES email
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: emails-service-storage
        - Version: 2012-10-17
          Statement:
            - Action:
                - 'apigateway:GET'
              Effect: Allow
              Resource: 'arn:aws:apigateway:us-east-1::/apikeys'
      Environment:
        Variables:
          ACCOUNT_API_KEY_NAME: emails-ApiAp-Q78YXqNItYEF
          ACCOUNT_API_URL: 'http://emails-account-api.bowland.link/'
          EMAIL_API_KEY_NAME: emails-ApiAp-fiLUXC7EH0ik
          EMAIL_API_URL: 'http://emails-email-api.bowland.link/'
          EMAIL_BUCKET: emails-service-storage
          EMAIL_FROM: do-not-reply@bowland.link
          EMAIL_REGION: us-east-1
          ERROR_EMAIL: dbowland1+emails-service-error@gmail.com
          QUEUE_API_KEY_NAME: emails-ApiAp-pIzQfk2pD24Q
          QUEUE_API_URL: 'http://emails-queue-api.bowland.link/'
      Tags:
        'created-by': 'emails-inbound-service'
        'created-for': 'emails'

  LambdaExecutePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt IncomingEmailFunction.Arn
      Principal: ses.amazonaws.com
      SourceAccount: !Ref AccountId

  IncomingEmailLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: IncomingEmailFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${IncomingEmailFunction}
      RetentionInDays: 30

  MXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: !Sub 'Email target for ${Subdomain}'
      HostedZoneName: bowland.link.
      Name: !Ref Subdomain
      ResourceRecords:
        - '10 inbound-smtp.us-east-1.amazonaws.com'
      TTL: 300
      Type: 'MX'

  # NOTE: Must be activated manually
  ReceiptRuleSet:
    Type: 'AWS::SES::ReceiptRuleSet'
    Properties:
      RuleSetName: !Ref Ruleset

  ReceiptRule:
    Type: AWS::SES::ReceiptRule
    Properties:
      Rule:
        Actions:
          - S3Action:
              BucketName: emails-service-storage
              ObjectKeyPrefix: 'inbound/'
          - LambdaAction:
              FunctionArn: !GetAtt IncomingEmailFunction.Arn
              InvocationType: 'Event'
        Enabled: true
        Name: !Sub 'rule-set-${Subdomain}'
        Recipients:
          - !Ref Subdomain
        ScanEnabled: true
      # This is not a typo, this should always be the active (production) rule set
      RuleSetName: emails-inbound-service
