AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Service to process inbound emails

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  EmailsApiKey:
    Type: String
    Description: API key for emails-email-api
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy
  QueueApiKey:
    Type: String
    Description: API key for emails-queue-api

Mappings:
  EnvironmentMap:
    prod:
      bucket: emails-service-storage
      corsDomain: https://email.dbowland.com
      domain: dbowland.com
      emailsApiUrl: 'https://emails-email-api-internal.dbowland.com/v1'
      logStreamFunction: log-subscriber
      project: emails-inbound-service
      queueApiUrl: 'https://emails-queue-api.dbowland.com/v1'
    test:
      bucket: emails-service-storage-test
      corsDomain: https://email.bowland.link
      domain: bowland.link
      emailsApiUrl: 'https://emails-email-api-internal.bowland.link/v1'
      logStreamFunction: log-subscriber-test
      project: emails-inbound-service-test
      queueApiUrl: 'https://emails-queue-api.bowland.link/v1'

Resources:
  # SES

  # NOTE: Must be activated manually
  ReceiptRuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: !FindInMap [EnvironmentMap, !Ref Environment, project]

  ReceiptRule:
    Type: AWS::SES::ReceiptRule
    DependsOn: [LambdaExecutePermission]
    Properties:
      Rule:
        Actions:
          - S3Action:
              BucketName: !Ref EmailBucket
              ObjectKeyPrefix: 'inbound/'
          - LambdaAction:
              FunctionArn: !GetAtt IncomingEmailProcessor.Arn
              InvocationType: 'Event'
        Enabled: true
        Name: !Sub
          - 'rule-set-${Domain}'
          - Domain: !FindInMap [EnvironmentMap, !Ref Environment, domain]
        Recipients:
          - !FindInMap [EnvironmentMap, !Ref Environment, domain]
        ScanEnabled: true
      # This is not a typo, this should always be the active (production) rule set
      RuleSetName: !FindInMap [EnvironmentMap, 'prod', project]

  # Route 53

  MXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: !Sub
        - 'Email target for ${Domain}'
        - Domain: !FindInMap [EnvironmentMap, !Ref Environment, domain]
      HostedZoneName: !Sub
        - '${Domain}.'
        - Domain: !FindInMap [EnvironmentMap, !Ref Environment, domain]
      Name: !FindInMap [EnvironmentMap, !Ref Environment, domain]
      ResourceRecords:
        - '10 inbound-smtp.us-east-1.amazonaws.com'
      TTL: 300
      Type: 'MX'

  # Lambda

  IncomingEmailProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/incoming-email.handleIncomingEmail
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Description: Incoming SES email
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: !Ref EmailBucket
      Environment:
        Variables:
          EMAILS_API_KEY: !Ref EmailsApiKey
          EMAILS_API_URL: !FindInMap [EnvironmentMap, !Ref Environment, emailsApiUrl]
          EMAIL_BUCKET: !Ref EmailBucket
          EMAIL_FROM: !Sub
            - 'do-not-reply@${Domain}'
            - Domain: !FindInMap [EnvironmentMap, !Ref Environment, domain]
          EMAIL_REGION: us-east-1
          QUEUE_API_KEY: !Ref QueueApiKey
          QUEUE_API_URL: !FindInMap [EnvironmentMap, !Ref Environment, queueApiUrl]
      Tags:
        'created-by': 'emails-inbound-service'
        'created-for': 'emails'
        'environment': !Ref Environment
      Timeout: 180
      Tracing: Active
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - src/handlers/incoming-email.ts

  LambdaExecutePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Sub '${IncomingEmailProcessor.Arn}'
      Principal: ses.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  # CloudWatch

  IncomingEmailLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: IncomingEmailProcessor
    Properties:
      LogGroupName: !Sub /aws/lambda/${IncomingEmailProcessor}
      RetentionInDays: 30
      Tags:
        - Key: 'created-by'
          Value: 'emails-inbound-service'
        - Key: 'created-for'
          Value: 'emails'
        - Key: 'environment'
          Value: !Ref Environment

  IncomingEmailLogGroupSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Sub
        - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Function}'
        - Function: !FindInMap [EnvironmentMap, !Ref Environment, logStreamFunction]
      FilterPattern: '[timestamp, uuid, level="ERROR", message]'
      LogGroupName: !Ref IncomingEmailLogGroup

  # S3

  EmailBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      BucketName: !FindInMap [EnvironmentMap, !Ref Environment, bucket]
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - POST
            AllowedOrigins:
              - !FindInMap [EnvironmentMap, !Ref Environment, corsDomain]
            ExposedHeaders:
              - Date
            Id: EmailCORS
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1096 # 3 years
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
            Status: Enabled
            Transitions:
              - TransitionInDays: 60
                StorageClass: STANDARD_IA
              - TransitionInDays: 180
                StorageClass: GLACIER_IR
          - ExpirationInDays: 1
            Prefix: attachments/
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: 'created-by'
          Value: 'emails-inbound-service'
        - Key: 'created-for'
          Value: 'emails'
        - Key: 'environment'
          Value: !Ref Environment
      VersioningConfiguration:
        Status: Enabled

  EmailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EmailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:PutObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${EmailBucket}/*'
            Principal:
              Service: ses.amazonaws.com
            Condition:
              StringLike:
                'aws:Referer':
                  - !Ref AWS::AccountId
